name: Deploy to azure static web apps

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Install
              shell: 'bash'
              run: |
                  npm ci

            - name: Build
              shell: 'bash'
              env:
                  PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
                  PUBLIC_BASE_URL: ${{ vars.PUBLIC_BASE_URL }}
              run: |
                  npm run build

            - name: 'Upload'
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2

            - name: 'Download'
              uses: actions/download-artifact@v2
              with:
                  name: build

            - name: Deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: 'upload'
                  app_location: '/'
                  output_location: '/dist'
                  skip_app_build: true
